swagger: '2.0'
info:
  title: Email Service
  description: Email service
  version: #version#
schemes:
  - https
produces:
  - application/json
basePath: /email/v1
paths:
  /template:
    post:
      summary: Create new template
      operationId: createTemplate
      consumes: 
      - multipart/form-data
      parameters:
      - name: name
        in: formData
        required: true
        description: template name
        type: string
      - name: locale
        in: formData
        description: Locale of the template
        type: string
      - name: file
        in: formData
        required: true
        description: the body of template
        type: file 
      responses:
        '201':
          description: Created
        '400':
          description: User Error
        '500':
          description: Unexpected error
    get:
      summary: Get template
      operationId: getTemplate
      parameters:
      - name: name
        in: query
        required: true
        type: string
      - name: locale
        in: query
        required: false
        type: string
      responses:
        '200':
          description: Success
          schema: 
            $ref: '#/definitions/Template'
        '400':
          description: User Error
        '500':
          description: Unexpected error
  /send:
    post:
      summary: Send email
      operationId: sendEmail
      parameters:
      - name: emailDescriptor
        in: body
        schema:
          $ref: '#/definitions/EmailDescriptor'
      responses:
        '202':
          description: Accepted
        '400':
          description: User Error
        '500':
          description: Unexpected error
            
definitions:
  Template:
    type: object
    properties:
      body:
        type: string
      name:
        type: string
      locale:
        type: string
  EmailDescriptor:
    type: object
    properties:
      subject:
        type: string
      to:
        type: array
        items:
          type: string
      cc:
        type: array
        items:
          type: string
      bcc: 
        type: array
        items:
          type: string
      from: 
        type: string
      messageKey: 
        type: string
        required: true
      locale: 
        type: string
      parameters:
        type: array
        items:
          $ref: '#/definitions/NameValuePair'
  NameValuePair:
    type: object
    properties:
      name:
        type: string
      value:
        type: string